language: generic
sudo: required #for all commands we need sudo
services:
  - docker

before_install: 
  - docker build -t altinilke/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true altinilke/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-541271734566"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
